name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     - name: Log in to GHCR
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Set build metadata
  id: meta
  run: |
    echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
    echo "BUILD=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
    echo "DEPLOYED_AT=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
          build-args: |
            APP_VERSION=${{ steps.meta.outputs.VERSION }}
            APP_BUILD=${{ steps.meta.outputs.BUILD }}
            APP_DEPLOYED_AT=${{ steps.meta.outputs.DEPLOYED_AT }}
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=${{ github.ref_name }}-${{ github.run_number }}

  render-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
ci
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build metadata
        id: meta
        run: |
          echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
          echo "BUILD=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "DEPLOYED_AT=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            APP_VERSION=${{ steps.meta.outputs.VERSION }}
            APP_BUILD=${{ steps.meta.outputs.BUILD }}
            APP_DEPLOYED_AT=${{ steps.meta.outputs.DEPLOYED_AT }}
